=== Veneiro/SEW-2023/EscritorioVirtual/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.uniovi.es"
xmlns="http://www.uniovi.es"
elementFormDefault="qualified">
  <xs:element name="rutas">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ruta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ruta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombreRuta"/>
        <xs:element ref="tipoRuta"/>
        <xs:element ref="medioTransporte"/>
        <xs:element ref="fechaInicio"/>
        <xs:element ref="horaInicio"/>
        <xs:element ref="duracion"/>
        <xs:element ref="agencia"/>
        <xs:element ref="descripcion"/>
        <xs:element ref="adecuadoPara"/>
        <xs:element ref="lugarInicio"/>
        <xs:element ref="direccionInicio"/>
        <xs:element ref="coordenadasInicioRuta"/>
        <xs:element ref="referencias"/>
        <xs:element ref="puntuacion"/>
        <xs:element ref="hitos"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombreRuta" type="xs:string"/>
  <xs:element name="tipoRuta" type="xs:string"/>
  <xs:element name="medioTransporte" type="xs:NCName"/>
  <xs:element name="fechaInicio" type="xs:string"/>
  <xs:element name="horaInicio" type="xs:NMTOKEN"/>
  <xs:element name="duracion" type="xs:string"/>
  <xs:element name="agencia" type="xs:string"/>
  <xs:element name="descripcion" type="xs:string"/>
  <xs:element name="adecuadoPara" type="xs:string"/>
  <xs:element name="lugarInicio" type="xs:NCName"/>
  <xs:element name="direccionInicio" type="xs:string"/>
  <xs:element name="coordenadasInicioRuta">
    <xs:complexType>
      <xs:attribute name="lat" use="required" type="xs:decimal"/>
      <xs:attribute name="long" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="referencia"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencia" type="xs:anyURI"/>
  <xs:element name="puntuacion" type="xs:integer"/>
  <xs:element name="hitos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="hito"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="hito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombreHito"/>
        <xs:element ref="descripcionHito"/>
        <xs:element ref="coordenadasHito"/>
        <xs:element ref="distanciaAnteriorHito"/>
        <xs:element ref="fotos"/>
        <xs:element ref="videos"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombreHito" type="xs:string"/>
  <xs:element name="descripcionHito" type="xs:string"/>
  <xs:element name="coordenadasHito">
    <xs:complexType>
      <xs:attribute name="lat" use="required"/>
      <xs:attribute name="long" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="distanciaAnteriorHito" type="xs:string"/>
  <xs:element name="fotos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="foto"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="foto">
    <xs:complexType/>
  </xs:element>
  <xs:element name="videos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="video"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="video">
    <xs:complexType/>
  </xs:element>
</xs:schema>

=== Veneiro/SEW-2023/EscritorioVirtual/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es rutas.xsd">
    <ruta>
        <nombreRuta>
            Tour desde Brujas
        </nombreRuta>
        <tipoRuta>
            Paisajística e Histórica
        </tipoRuta>
        <medioTransporte>
            Minibus
        </medioTransporte>
        <fechaInicio>
            7 de agosto
        </fechaInicio>
        <horaInicio>
            9:00
        </horaInicio>
        <duracion>
            9 horas
        </duracion>
        <agencia>
            GetYourGuide
        </agencia>
        <descripcion>
            Es un tour que sale desde Brujas para visitar los principales campos de batalla donde sucedieron algunos de los enfrentamientos más importantes de la Primera Guerra Mundial.

            Este tour nos llevará hasta los búnkers, elemento clave de aquella guerra, y a conocer la ciudad de Yprés que sufrió la devastación en aquellos años.
            
            El tour, de 9 horas, incluye el transporte en autocar, el guía, las entradas al museo y un almuerzo en Hooge Crater.
        </descripcion>
        <adecuadoPara>
            Mayores de 8 años
        </adecuadoPara>
        <lugarInicio>
            Brujas
        </lugarInicio>
        <direccionInicio>
            La zona Kiss and Ride frente a la estación de tren, cerca del Belchicken Foodbar y del Subway Sandwich bar de Brujas
        </direccionInicio>
        <coordenadasInicioRuta lat="51.198006" long="3.219436"></coordenadasInicioRuta>
        <referencias>
            <referencia>https://sobrebelgica.com/2021/03/01/visita-a-los-campos-de-batalla-de-la-i-guerra-mundial-en-flandes/</referencia>
            <referencia>https://www.getyourguide.es/brujas-l854/tour-historico-i-guerra-mundial-y-flandes-en-monovolumen-t14280/</referencia>
        </referencias>
        <puntuacion>
            10
        </puntuacion>
        <hitos>
            <hito>
                <nombreHito>
                    Passchendaele New British Cemetery
                </nombreHito>
                <descripcionHito>Cementerio de la Primera Guerra Mundial</descripcionHito>
                <coordenadasHito lat="50.90445196368657" long="3.0106864040486663"></coordenadasHito>
                <distanciaAnteriorHito>0Km</distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
                    <video></video>
                    <video></video>
                    <video></video>
                </videos>
            </hito>
            <hito>
                <nombreHito>
                    Puerta de Menin
                </nombreHito>
                <descripcionHito>La Puerta de Menin es un monumento de guerra en Ypres, Bélgica dedicado a los soldados británicos y de la Commonwealth que murieron en el saliente de Ypres en la Primera Guerra Mundial y cuyas tumbas son desconocidas</descripcionHito>
                <coordenadasHito lat="50.852053" long="2.89107"></coordenadasHito>
                <distanciaAnteriorHito>11Km</distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
                    <video></video>
                    <video></video>
                    <video></video>
                </videos>
            </hito>
            <hito>
                <nombreHito>
                    Campos de Amapolas de Flandes
                </nombreHito>
                <descripcionHito>De 1914 a 1918, los Campos de Flanders fueron un importante escenario de batallala en el Frente occidental durante la Primera Guerra Mundial. Aquí, en el fragor de la batalla, un millón de soldados de más de 50 países diferentes resultaron heridos, desaparecidos o muertos. Ciudades y pueblos enteros fueron destruidos, su población se tuvo que dispersar por Europa y más allá. La destrucción de la ciudad de Ypres y las condiciones brutales soportadas durante la Batalla de Passchendaele (Tercera Batalla de Ypres) se convirtieron en símbolos mundiales del poco sentido que tenía la guerra. Hoy, la región pacífica sigue siendo testigo de esta historia a través de sus monumentos, museos, cementerios y las innumerables historias individuales que la vinculan con el mundo.</descripcionHito>
                <coordenadasHito lat="" long=""></coordenadasHito>
                <distanciaAnteriorHito></distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
                    <video></video>
                    <video></video>
                    <video></video>
                </videos>
            </hito>
        </hitos>
    </ruta>
    <ruta>
        <nombreRuta>
            Crucero por Brujas
        </nombreRuta>
        <tipoRuta>
            Arquitectura y Monumentos
        </tipoRuta>
        <medioTransporte>
            Barco
        </medioTransporte>
        <fechaInicio>
            10 de Junio
        </fechaInicio>
        <horaInicio>
            13:00
        </horaInicio>
        <duracion>
            2-2,5 horas
        </duracion>
        <agencia>
            GetYourGuide
        </agencia>
        <descripcion>
            Reúnete con tu guía en la Plaza del Mercado, en el corazón de la ciudad. Explora el centro histórico con un guía local cualificado. Conoce la historia local, las leyendas y los lugares de interés.

            Descubre la calle más estrecha, la hermosa basílica del siglo XII y las estatuas doradas del impresionante palacio de justicia. A continuación, explora el antiguo mercado de pescado, rodeado de 126 columnas.

            A continuación, embárcate en la segunda parte del recorrido. Sube a tu barco en el muelle para hacer un crucero por los canales. Navega junto a fachadas cubiertas de hiedra y bajo puentes mientras tu capitán te explica los bellos lugares. Admira pintorescas casas y lugares emblemáticos desde el agua.

            Pasea por el Muelle del Rosario y entra en una chocolatería. Prueba el chocolate artesanal. No sólo es fresco, sino también cuidadosamente elaborado. El resultado es una gran variedad de sabrosos rellenos y formas. ¡Afina tus sentidos!

            Sigue descubriendo los lugares más destacados, como el palacio Gruuthuse, el romántico Puente de Bonifacio y la Iglesia de Nuestra Señora. Déjate sorprender por el jardín oculto de una casa de limosnas. ¡Vive Brujas en todos sus fascinantes aspectos!
        </descripcion>
        <adecuadoPara>
            Personas sin problemas de movilidad
        </adecuadoPara>
        <lugarInicio>
            Brujas
        </lugarInicio>
        <direccionInicio>
            Delante del edificio gris de Historium, en la Plaza del Mercado
        </direccionInicio>
        <coordenadasInicioRuta lat="51.209129" long=""></coordenadasInicioRuta>
        <referencias>
            <referencia>https://www.getyourguide.es/brujas-l854/brujas-crucero-en-barco-y-visita-guiada-privada-a-pie-t399508?ranking_uuid=912d5fdb-699e-4f7d-b6d7-0593d4257645&amp;lang=en&amp;_pc=1,1</referencia>
        </referencias>
        <puntuacion>
            9
        </puntuacion>
        <hitos>
            <hito>
                <nombreHito>
                    Basílica de Santa Sangre
                </nombreHito>
                <descripcionHito></descripcionHito>
                <coordenadasHito lat="" long=""></coordenadasHito>
                <distanciaAnteriorHito></distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
                    <video></video>
                    <video></video>
                    <video></video>
                </videos>
            </hito>
            <hito>
                <nombreHito>
                    Los Cuatro jinetes del Apocalipsis
                </nombreHito>
                <descripcionHito></descripcionHito>
                <coordenadasHito  lat="" long=""></coordenadasHito>
                <distanciaAnteriorHito></distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
                    <video></video>
                    <video></video>
                    <video></video>
                </videos>
            </hito>
            <hito>
                <nombreHito>
                    Museo Gruuthuse
                </nombreHito>
                <descripcionHito>

                </descripcionHito>
                <coordenadasHito  lat="" long=""></coordenadasHito>
                <distanciaAnteriorHito>

                </distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
                    <video></video>
                    <video></video>
                    <video></video>
                </videos>
            </hito>
        </hitos>
    </ruta>
    <ruta>
        <nombreRuta>
            Tour de Amberes
        </nombreRuta>
        <tipoRuta>
            Paisajística e Histórica
        </tipoRuta>
        <medioTransporte>
            Minibus
        </medioTransporte>
        <fechaInicio>
            10 de agosto
        </fechaInicio>
        <horaInicio>
            10:00
        </horaInicio>
        <duracion>
            6 horas
        </duracion>
        <agencia>
            GetYourGuide
        </agencia>
