=== Veneiro/SEW-2023/EscritorioVirtual/xml/rutas.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (nombreRuta,tipoRuta,medioTransporte,fechaInicio,horaInicio,
                duracion,agencia,descripcion,adecuadoPara,lugarInicio,
                direccionInicio,coordenadasInicioRuta,referencias,puntuacion,
                hitos)>
<!ELEMENT nombreRuta (#PCDATA)>
<!ELEMENT tipoRuta (#PCDATA)>
<!ELEMENT medioTransporte (#PCDATA)>
<!ELEMENT fechaInicio (#PCDATA)>
<!ELEMENT horaInicio (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT adecuadoPara (#PCDATA)>
<!ELEMENT lugarInicio (#PCDATA)>
<!ELEMENT direccionInicio (#PCDATA)>
<!ELEMENT coordenadasInicioRuta EMPTY>
<!ATTLIST coordenadasInicioRuta
  lat CDATA #REQUIRED
  long CDATA #REQUIRED
  ele CDATA #REQUIRED>
<!ELEMENT referencias (referencia+)>
<!ELEMENT puntuacion (#PCDATA)>
<!ELEMENT hitos (hito+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT hito (nombreHito,descripcionHito,coordenadasHito,
                distanciaAnteriorHito,fotos,videos)>
<!ELEMENT nombreHito (#PCDATA)>
<!ELEMENT descripcionHito (#PCDATA)>
<!ELEMENT coordenadasHito (#PCDATA)>
<!ATTLIST coordenadasHito
  lat CDATA #REQUIRED
  long CDATA #REQUIRED
  ele CDATA #REQUIRED>
<!ELEMENT distanciaAnteriorHito (#PCDATA)>
<!ELEMENT fotos (foto+)>
<!ELEMENT videos (video+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT video (#PCDATA)>

=== Veneiro/SEW-2023/Escritorio Virtual/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
    <ruta>
        <nombreRuta> Tour desde Brujas </nombreRuta>
        <tipoRuta> Paisajística e Histórica </tipoRuta>
        <medioTransporte> Minibus </medioTransporte>
        <fechaInicio> 7 de agosto </fechaInicio>
        <horaInicio> 9:00 </horaInicio>
        <duracion> 9 horas </duracion>
        <agencia> GetYourGuide </agencia>
        <descripcion> Es un tour que sale desde Brujas para visitar los principales campos de
            batalla donde sucedieron algunos de los enfrentamientos más importantes de la Primera
            Guerra Mundial. Este tour nos llevará hasta los búnkers, elemento clave de aquella
            guerra, y a conocer la ciudad de Yprés que sufrió la devastación en aquellos años. El
            tour, de 9 horas, incluye el transporte en autocar, el guía, las entradas al museo y un
            almuerzo en Hooge Crater. </descripcion>
        <adecuadoPara> Mayores de 8 años </adecuadoPara>
        <lugarInicio> Brujas </lugarInicio>
        <direccionInicio> La zona Kiss and Ride frente a la estación de tren, cerca del Belchicken
            Foodbar y del Subway Sandwich bar de Brujas </direccionInicio>
        <coordenadasInicioRuta lat="51.198006" long="3.219436" ele="4.0"></coordenadasInicioRuta>
        <referencias>
            <referencia>
                https://sobrebelgica.com/2021/03/01/visita-a-los-campos-de-batalla-de-la-i-guerra-mundial-en-flandes/</referencia>
            <referencia>
                https://www.getyourguide.es/brujas-l854/tour-historico-i-guerra-mundial-y-flandes-en-monovolumen-t14280/</referencia>
        </referencias>
        <puntuacion> 10 </puntuacion>
        <hitos>
            <hito>
                <nombreHito> Passchendaele New British Cemetery </nombreHito>
                <descripcionHito>Cementerio de la Primera Guerra Mundial</descripcionHito>
                <coordenadasHito lat="50.90445196368657" long="3.0106864040486663" ele="48.0"></coordenadasHito>
                <distanciaAnteriorHito>0Km</distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
                    <video></video>
                    <video></video>
                    <video></video>
                </videos>
            </hito>
            <hito>
                <nombreHito> Puerta de Menin </nombreHito>
                <descripcionHito>La Puerta de Menin es un monumento de guerra en Ypres, Bélgica
                    dedicado a los soldados británicos y de la Commonwealth que murieron en el
                    saliente de Ypres en la Primera Guerra Mundial y cuyas tumbas son desconocidas</descripcionHito>
                <coordenadasHito lat="50.852053" long="2.89107" ele="22.8"></coordenadasHito>
                <distanciaAnteriorHito>11.0</distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
                    <video></video>
                    <video></video>
                    <video></video>
                </videos>
            </hito>
            <hito>
                <nombreHito> Campos de Amapolas de Flandes </nombreHito>
                <descripcionHito>De 1914 a 1918, los Campos de Flanders fueron un importante
                    escenario de batalla en el Frente occidental durante la Primera Guerra
                    Mundial. Aquí, en el fragor de la batalla, un millón de soldados de más de 50
                    países diferentes resultaron heridos, desaparecidos o muertos. Ciudades y
                    pueblos enteros fueron destruidos, su población se tuvo que dispersar por Europa
                    y más allá. La destrucción de la ciudad de Ypres y las condiciones brutales
                    soportadas durante la Batalla de Passchendaele (Tercera Batalla de Ypres) se
                    convirtieron en símbolos mundiales del poco sentido que tenía la guerra. Hoy, la
                    región pacífica sigue siendo testigo de esta historia a través de sus
                    monumentos, museos, cementerios y las innumerables historias individuales que la
                    vinculan con el mundo.</descripcionHito>
                <coordenadasHito lat="50.874300151859174" long="3.453939947997965" ele="34.5"></coordenadasHito>
                <distanciaAnteriorHito>46.0</distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
                    <video></video>
                    <video></video>
                    <video></video>
                </videos>
            </hito>
        </hitos>
    </ruta>
    <ruta>
        <nombreRuta> Crucero por Brujas </nombreRuta>
        <tipoRuta> Arquitectura y Monumentos </tipoRuta>
        <medioTransporte> Barco </medioTransporte>
        <fechaInicio> 10 de Junio </fechaInicio>
        <horaInicio> 13:00 </horaInicio>
        <duracion> 2-2,5 horas </duracion>
        <agencia> GetYourGuide </agencia>
        <descripcion> Reúnete con tu guía en la Plaza del Mercado, en el corazón de la ciudad.
            Explora el centro histórico con un guía local cualificado. Conoce la historia local, las
            leyendas y los lugares de interés. Descubre la calle más estrecha, la hermosa basílica
            del siglo XII y las estatuas doradas del impresionante palacio de justicia. A
            continuación, explora el antiguo mercado de pescado, rodeado de 126 columnas. A
            continuación, embárcate en la segunda parte del recorrido. Sube a tu barco en el muelle
            para hacer un crucero por los canales. Navega junto a fachadas cubiertas de hiedra y
            bajo puentes mientras tu capitán te explica los bellos lugares. Admira pintorescas casas
            y lugares emblemáticos desde el agua. Pasea por el Muelle del Rosario y entra en una
            chocolatería. Prueba el chocolate artesanal. No sólo es fresco, sino también
            cuidadosamente elaborado. El resultado es una gran variedad de sabrosos rellenos y
            formas. ¡Afina tus sentidos! Sigue descubriendo los lugares más destacados, como el
            palacio Gruuthuse, el romántico Puente de Bonifacio y la Iglesia de Nuestra Señora.
            Déjate sorprender por el jardín oculto de una casa de limosnas. ¡Vive Brujas en todos
            sus fascinantes aspectos! </descripcion>
        <adecuadoPara> Personas sin problemas de movilidad </adecuadoPara>
        <lugarInicio> Brujas </lugarInicio>
        <direccionInicio> Delante del edificio gris de Historium, en la Plaza del Mercado </direccionInicio>
        <coordenadasInicioRuta lat="51.20894096503173" long="3.224689188301902" ele="11.1"></coordenadasInicioRuta>
        <referencias>
            <referencia>
                https://www.getyourguide.es/brujas-l854/brujas-crucero-en-barco-y-visita-guiada-privada-a-pie-t399508?ranking_uuid=912d5fdb-699e-4f7d-b6d7-0593d4257645&amp;lang=en&amp;_pc=1,1</referencia>
        </referencias>
        <puntuacion> 9 </puntuacion>
        <hitos>
            <hito>
                <nombreHito> Basílica de Santa Sangre </nombreHito>
                <descripcionHito>La Basílica de Santa Sangre es una basílica menor de culto católico
                    ubicada en Brujas, Bélgica. Construida originalmente en el siglo xii como
                    capilla de la residencia del conde de Flandes, la iglesia alberga una venerada
                    reliquia de la sangre de Cristo, supuestamente recogida por José de Arimatea y
                    traída de Tierra Santa por Teodorico de Alsacia, conde de Flandes. Construida
                    entre 1134 y 1157, fue consagrada como basílica menor en 1923. La basílica, del
                    siglo xii, está situada en la Plaza Burg, y consiste en una capilla inferior y
                    otra superior. La capilla inferior, dedicada a San Basilio el Grande, es una
                    oscura estructura románica que se mantiene prácticamente en estado original. La
                    reliquia se encuentra en la capilla superior, reconstruida en estilo gótico
                    durante el siglo xvi, y renovada numerosas veces durante el siglo xix en estilo
                    neogótico.</descripcionHito>
                <coordenadasHito lat="51.20827540039973" long="3.226620028760691" ele="12.0"></coordenadasHito>
                <distanciaAnteriorHito>0.12</distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
                    <video></video>
                    <video></video>
                    <video></video>
                </videos>
            </hito>
            <hito>
                <nombreHito> Los Cuatro jinetes del Apocalipsis </nombreHito>
                <descripcionHito>Estas esculturas fueron creadas por Rik Poot, y es él el que nombró
                    en este caso, como La Revolución al Jinete blanco, ya que se consideran
                    diferentes opciones para este. Hay varias teorías que tienen un punto de vista
                    más positivo y lo ven como la Esperanza o Jesucristo como tal.</descripcionHito>
                <coordenadasHito lat="51.20538342403609" long="3.2255953479023542" ele="6.6"></coordenadasHito>
                <distanciaAnteriorHito>4.8</distanciaAnteriorHito>
                <fotos>
                    <foto></foto>
                    <foto></foto>
                    <foto></foto>
                </fotos>
                <videos>
